name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Pack extension
        run: |
          zip -r "windbar@mikanight.shell-extension.zip" \
            metadata.json \
            extension.js \
            prefs.js \
            cli.js \
            parser.js \
            windbar-connected.svg \
            windbar-disconnected.svg \
            schemas/

      - name: Upload release
        uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65 # v2
        with:
          files: windbar@mikanight.shell-extension.zip
